### Get all contacts
GET http://localhost:3000/contacts
Content-Type: application/json

###

### Get a single contact 
GET http://localhost:3000/contacts/69064ee596c0157c44c90979
Content-Type: application/json


